language: java

jdk:
  - oraclejdk8
  
# Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
addons:
apt:
packages:
  - oracle-java8-installer  # this fixes the alert symbol error.

after_success:
  - bash <(curl -s https://codecov.io/bash)
